[versions]
assertj = "3.27.2"
compose = "1.7.0"
coroutines = "1.10.1"
jvmToolchain = "21"
kotlin = "2.0.21"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "compose" }
compose-desktop-ui-test-junit4 = { module = "org.jetbrains.compose.desktop:ui-test-junit4", version.ref = "compose" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material-icons-extended:material-icons-extended", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
compose-ui-test = { module = "org.jetbrains.compose.ui:test", version.ref = "compose" }
kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }